proxy:

  authentication: simple
  users:
  - name: demo
    password: demo
  ldap:
    url: ldap://ldap.forumsys.com:389/dc=example,dc=com
    user-dn-pattern: uid={0}
    group-search-filter: (uniqueMember={0})
    manager-dn: cn=read-only-admin,dc=example,dc=com
    manager-password: password
  keycloak:
    realm: demo
    auth-server-url: http://localhost:8081/auth
    resource: shinyproxy
    credentials-secret: 38328702-062c-4e7d-86bf-50f184dad34c

  docker:
    url: http://localhost:2375

  #usage-stats-url: http://localhost:8086/write?db=shinyproxy_usagestats

  specs:
  - id: r-3.4.4
    container-specs:
    - image: "registry.openanalytics.eu/private/rconsoleproxy"
      port-mapping:
        default: 8080
  - id: 01_hello
    container-specs:
    - image: "openanalytics/shinyproxy-demo"
      cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
      port-mapping:
        default: 3838
    runtime-setting-specs:
    - name: container.memory
